language: python
python:
  - "2.7"
cache: pip
before_install:
  - pip install pytest pytest-cov
  - pip install coveralls
install:
  - pip install -r requirements.txt
script:
  - coverage run sumatra_spec.py
after_success:
  - coveralls
